Website = "https://github.com/ErikKalkoken/janice"

[Details]
  Icon = "icon.png"
  Name = "Janice"
  ID = "io.github.erikkalkoken.janice"
  Version = "0.2.3"
  Build = 2

[Release]
  BuildName = "janice"

[LinuxAndBSD]
  GenericName = "JSON viewer"
  Categories = ["Utility"]
  Comment = "View large JSON files"
  Keywords = ["json", "viewer"]
